//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WelcomeSOAPXMLClient.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IWelcomeSOAPXMLService")]
    public interface IWelcomeSOAPXMLService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWelcomeSOAPXMLService/Welcome", ReplyAction="http://tempuri.org/IWelcomeSOAPXMLService/WelcomeResponse")]
        string Welcome(string yourName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWelcomeSOAPXMLServiceChannel : WelcomeSOAPXMLClient.ServiceReference.IWelcomeSOAPXMLService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WelcomeSOAPXMLServiceClient : System.ServiceModel.ClientBase<WelcomeSOAPXMLClient.ServiceReference.IWelcomeSOAPXMLService>, WelcomeSOAPXMLClient.ServiceReference.IWelcomeSOAPXMLService {
        
        public WelcomeSOAPXMLServiceClient() {
        }
        
        public WelcomeSOAPXMLServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WelcomeSOAPXMLServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WelcomeSOAPXMLServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WelcomeSOAPXMLServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Welcome(string yourName) {
            return base.Channel.Welcome(yourName);
        }
    }
}
