//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WelcomeRESTXMLClient.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IWelcomeRESTXMLService")]
    public interface IWelcomeRESTXMLService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWelcomeRESTXMLService/Welcome", ReplyAction="http://tempuri.org/IWelcomeRESTXMLService/WelcomeResponse")]
        string Welcome(string yourName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWelcomeRESTXMLServiceChannel : WelcomeRESTXMLClient.ServiceReference.IWelcomeRESTXMLService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WelcomeRESTXMLServiceClient : System.ServiceModel.ClientBase<WelcomeRESTXMLClient.ServiceReference.IWelcomeRESTXMLService>, WelcomeRESTXMLClient.ServiceReference.IWelcomeRESTXMLService {
        
        public WelcomeRESTXMLServiceClient() {
        }
        
        public WelcomeRESTXMLServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WelcomeRESTXMLServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WelcomeRESTXMLServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WelcomeRESTXMLServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Welcome(string yourName) {
            return base.Channel.Welcome(yourName);
        }
    }
}
