//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackjackClient.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IBlackjackService", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IBlackjackService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlackjackService/DealCard", ReplyAction="http://tempuri.org/IBlackjackService/DealCardResponse")]
        string DealCard();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlackjackService/Shuffle", ReplyAction="http://tempuri.org/IBlackjackService/ShuffleResponse")]
        void Shuffle();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBlackjackService/GetHandValue", ReplyAction="http://tempuri.org/IBlackjackService/GetHandValueResponse")]
        int GetHandValue(string dealt);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBlackjackServiceChannel : BlackjackClient.ServiceReference.IBlackjackService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BlackjackServiceClient : System.ServiceModel.ClientBase<BlackjackClient.ServiceReference.IBlackjackService>, BlackjackClient.ServiceReference.IBlackjackService {
        
        public BlackjackServiceClient() {
        }
        
        public BlackjackServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BlackjackServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BlackjackServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BlackjackServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string DealCard() {
            return base.Channel.DealCard();
        }
        
        public void Shuffle() {
            base.Channel.Shuffle();
        }
        
        public int GetHandValue(string dealt) {
            return base.Channel.GetHandValue(dealt);
        }
    }
}
